### PR TITLE
Removed unused variables and unused code

### PR DESCRIPTION
**Pull request by durgaswaroop**
This is list of all the changes I have made

1. The line `adjusted_values = list(values)` is not needed as the `adjusted_values` gets reassigned in the very next line. Removed that. 
2. The long description in setup.py was pointing to `description`. Modified it to `long_description` instead. [Mentioned in #4]
3. Removed two cases in if-else block to decide the ascii character as they will never be reached
4. Removed some more code that is not needed

### CODE REVIEW

**Comment by durgaswaroop** [comment]
Can someone look at why the build has failed? The errors don't seem to correspond to the changes I have made.

**Comment by durgaswaroop** [comment]
@scallister I have made a couple of changes. Please take a look at those. 

Also, Is this project being maintained anymore?

**Comment by scallister** [comment]
@durgaswaroop I no longer work at LinkedIn.com, but I am currently the maintainer.

**Comment by scallister** [comment]
@durgaswaroop I've pushed these changes to PyPI as version `1.0.5`. Thanks again for your PR.

**Comment by durgaswaroop** [comment]
Thank you @scallister. :)

**Pull request merged**
